### ISSUE TITLE
NetworkConfig mismatch.

### ISSUE THREAD

**Issue by DeCat4** [Beauver/ExtraTerminalCommands#20]
when someone tries to join me if i have this mod and terminal api enabled they get this error, they don't get it if only terminal api is enabled. I'm also using morecompany i haven't tested without it yet.

Could this be related to the copying host settings thing? i can't find a config for that in the file

![image](https://github.com/Beauver/ExtraTerminalCommands/assets/57727851/e0f5ee2e-6e9f-4917-9d4a-c03334008184)

**Comment by Beauver** [comment]
If this happens when hosting:
- I have simply no idea why, I haven't updated the mod as of like 2 months, stuff may of have broken in the meantime.

If this happens when joining:
- Your ExtraTerminalCommands configuration file isn't the exact same as the host's configuration file. 
- I implemented my own way of syncing these two files, though it doesn't seem to be appreciated by system.

In general I am unsure if I will even continue working on this mod as this mod was intentionally made for my friends to enjoy, currently we've outgrown lethal and thus am unsure if I'll keep working on it.
There are plenty of other mods that most likely do the same as mine which are being constantly updated, I recommend you may want to try out those.

Thanks for understanding
