### ISSUE TITLE
config mismatch makes Random Price useless

### ISSUE THREAD

**Issue by Sebiann** [Beauver/ExtraTerminalCommands#4]
if the host has random price set to 100 and a player joins with it set to 0. It doesn't cost them to run random

**Comment by Beauver** [comment]
Acknowledged, will look into a fix

**Comment by Beauver** [comment]
This issue should be fixed as I've now implemented a system which syncs the important config values with the host, these are temporary and do not change your actual config settings, do not fear.

If this in fact did not seem to work, please reopen this or create a new issue.

Bug should be fixed in 1.2.2 or 1.3.0
